### ISSUE TITLE
exclude journal-filled quests from "quests completed" metric

### ISSUE THREAD

**Issue by MichaelEbert** [MichaelEbert/OblivionProgressTracker#2]
generic monkey patch file??

**Comment by MichaelEbert** [comment]
Maybe this is the same sort of thing we'll have to do with oblivion gates

**Comment by MichaelEbert** [comment]
so this is now possible, but excluding them from that excludes them from progrss calculation altogether.

**Comment by MeemawHustlin** [comment]
I'm thinking the best solution to this for now would be to not internally change the tracking of these at all, but if possible change the checklist overview to have separate sections since that's the only part of the entire website where the user really needs to see the difference between these objectives.

**Comment by MichaelEbert** [comment]
Yeah, easiest way would be to split it into its own section :/.

**Comment by MeemawHustlin** [comment]
Let's finally put this one to rest lol. The checklist simply has a hoverable note on that overview explaining the value discrepancy in-game and how to verify it against the checklist values. The likelihood of people not finding this hover is low since it sticks out and is in huge text at the top of the checklist. We can reopen this if users have problems with this often.
