### ISSUE TITLE
[Map UI] Need more visual labeling for fixed/double fame/set layout gates

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#209]
The small colored letters are pretty hard to see unless you zoom very far in on each oblivion gate. In the v3 map, we opted for more visual labeling with colors being a secondary way to identify gates:

- pink circled gates are fixed locations
- Green plus signs in the top right corner mean double fame
- blue asterisks in the bottom left corner mean fixed layouts

I think icons that are larger than these letters would work better, or at the very least making the letters larger and spatially overlapping the edges of the icons more.

**Comment by MichaelEbert** [comment]
It is probably a good thing to differentiate harder between random and fixed location gates.

I'm wondering if the other 2 categories need to be displayed as distinctly as they were in v3.
1 fame vs 2 fame doesn't matter unless you're manually counting fame because you screwed up somewhere, at which point a small icon is probably OK.
Now that we're not rerolling gate layouts, the fixed vs non-fixed layouts don't really matter either, right?

If we can narrow this down to only fixed vs random location gates, then we can explore more options, like a special border, or the "undiscovered" color scheme for random gates.

**Comment by MeemawHustlin** [comment]
Actually yeah that's a good point, since the checklist does the logic for us, the player doesn't even really need to be aware of which gates are double fame or fixed layout since the guide automates their gate closing process. I'd say just making the fixed gates label more visual is good then. A pink circle around these gates seems good enough, but I'm open to other ideas you might have.

**Comment by MichaelEbert** [comment]
I think a circle looks a bit clumsy, but IDK. it might work well.
I added a pink border around the edge but its still not great.
You can edit images/Icon_Overlay_Fixed.png to what we want it to be.

**Comment by MeemawHustlin** [comment]
I agree that the labeling of gates is much less important now with the new tech. Casual players really only need to see the fixed ones clearly, and the slightly updated pink border matches the rounded edges of the icons now so it fits in a little better. Let's call this good enough for now, down the road someone might have a better idea but functionally it is where it needs to be already.
