### ISSUE TITLE
Should be able to check off heaven stones/wayshrines

### ISSUE THREAD

**Issue by MichaelEbert** [MichaelEbert/OblivionProgressTracker#259]

**Comment by MichaelEbert** [comment]
Heaven stones: map place is not the same as power got.

- We could ref, but then you can't check off power via the stone
- Maybe make the power have the map stone icon? Kinda a hack though.
- separate loc field? Might work for oblivion gates closed as well...

Wayshrines: multiple wayshrines for the same blessing .
- checking one greys out the other?
- but on checklist, need to be able to check off via the blessing?? Idk

**Comment by MeemawHustlin** [comment]
Not sure of the best overall solution as far as code goes, but ideally the end user has the following:

There is only a single Heaven Stone for each greater power on the checklist, so checking the checklist box or clicking the map icon for that stone should toggle both, but the icon on the map should stay as the heaven stone icon for accuracy, and the spell icon should stay on the checklist for ease of locating them when verifying they are in the player's spell list.

Wayshrines have multiple instances of themselves, and getting any one of these effectively checks all copies of itself off, so clicking either on the checklist icon for that wayshrine or on any one of the map icons should toggle all instances of itself on both those pages. Greying out seems unnecessary in this case since the player effectively will be able to visit each Wayshrine and see it is no longer interactive due to being obtained, whereas things like random oblivion will be unable to ever be encountered after others were obtained, so greying those out makes more sense.
