### ISSUE TITLE
Confusing ID naming scheme

### ISSUE THREAD

**Issue by lukepk** [MichaelEbert/OblivionProgressTracker#44]
Currently, in json files under data/ the IDs are all referred to as formIDs.

However currently the NPC data specifically uses the RefID (rather than the base ID), and item data (eg books) uses the BaseID. UESP wiki pages for NPCs includes both RefID and BaseID, for items includes only BaseID (shown as ID).

In both cases we are calling this field formID, This is confusing as:

- Form IDs aren't listed anywhere on the wiki
- Its not documented (as far as I can tell) that formID in data/npc.json means RefID and not BaseID

Potentially related to #20

**Comment by MichaelEbert** [comment]
The underlying name for refID and baseID is formID, as mentioned in https://en.uesp.net/wiki/Oblivion:Form_ID
you're right that it's not documented that for NPCs, we use refID while for the rest we use baseid.
For nirnroot, we're going to use refID again.
not sure how to fix this. maybe we say which one in the beginning of the json? or make it an external document, since its only really useful for contributing?

**Comment by lukepk** [comment]
We could also rename the fields in the JSON files to represent what they actually are (e.g. call them refID and baseID rather than calling them all formID). 
Shouldn't be too difficult of a change and is more "self documenting".

Not sure if calling the fields formID is benefitting us in some way I can't see?

**Comment by MichaelEbert** [comment]
The most obvious impact is that we'd now have to check for both refID and baseID in all of the code that consumes these lists.

**Comment by MichaelEbert** [comment]
Few more things:
there are elements like skills that don't have a formID, would I give them a refID or baseID?
The save file (and thusly Valarnin's save reader) uses formID, so we'd have to convert back and forth anyways
